### ISSUE TITLE
Doesn't run on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [Songtech-0912/Prometheus-Project#1] opened 2020-08-16 19:59 UTC
Hi, thanks for making an AppImage. Any chance you could build it on Ubuntu xenial?

The currently available binary was built on a too new distribution, hence doesn't run on Ubuntu xenial:

```
libm.so.6: version `GLIBC_2.27' not found (required by Instant-Meshes)
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/2258

**Comment by Songtech-0912** [comment] 2020-08-16 22:01
Yes, I will definitely build one for Ubuntu xenial. Thanks for pointing out the issue @probonopd .

**Comment by Songtech-0912** [comment] 2020-08-17 19:55
@probonopd I've compiled an appimage that should work on Ubuntu Xenial. Try it [here](https://github.com/Songtech-0912/Prometheus-Project/releases/tag/v1.0-beta) and tell me if it works.

**Comment by probonopd** [comment] 2020-08-17 20:12
Getting `GLFW error 65544: X11: RandR gamma ramp support seems broken`, which could well be because I am running the test on a headless server. Is anything special required?

**Comment by Songtech-0912** [comment] 2020-08-17 20:23
Your issue seems to be a frequent issue on a headless server (you might want to see [this](https://github.com/glfw/glfw/issues/1004)). It might be related to using Ubuntu Xenial (which has an older version of `glfw`, and the bug seems to be only present in `glfw =<3.2`). I'll try to find a workaround for it.

**Comment by Songtech-0912** [comment] 2020-08-17 22:03
@probonopd I've recompiled Instant Meshes with a newer version of `glfw`. You can download it [here](https://gofile.io/d/CbSUpw). It seems to have no issue running on a dual-booted Ubuntu Xenial. Tell me if it works.

**Comment by probonopd** [comment] 2020-08-17 22:11
Unfortunately our automated test needs an URL to an AppImage.

**Comment by Songtech-0912** [comment] 2020-08-17 22:21
Okay, I've published it as a release; the direct link to the AppImage is [this](https://github.com/Songtech-0912/Prometheus-Project/releases/download/v1.0-beta.2/Instant_Meshes-x86_64.AppImage)

**Comment by probonopd** [comment] 2020-08-17 22:30
```
Running in GUI mode, start with -h for instructions on batch mode.

GLNUMBER_OF_WINDOWS: 0

ERROR: Could not find a single window on screen :-(
```

Might well be that our test script is somehow at fault though.

**Comment by Songtech-0912** [comment] 2020-08-17 22:33
Does your script have more detailed logging output? I could look through it and check what is wrong.

**Comment by probonopd** [comment] 2020-08-17 22:38
Full output is here: https://api.travis-ci.org/v3/job/718785049/log.txt

**Comment by Songtech-0912** [comment] 2020-08-17 22:43
Here's a [possible solution](https://gist.github.com/youandhubris/1de044c3abdc5393ae0f545002c34bd5) I found on Github gists. It seems that the issue mostly occurs if you use a dual monitor setup.

Basically the issue is a malfunctioning driver, usually of an improperly enabled/installed monitor. It might work if you can find which driver is causing the issue, and reinstall it.

**Comment by Songtech-0912** [comment] 2020-08-21 00:59
@probonopd Have you found a solution to your issue?

**Comment by probonopd** [comment] 2020-08-21 06:54
No, as the solution posted above is about Windows ;-/

**Comment by Songtech-0912** [comment] 2020-08-21 19:30
Okay, I will keep searching for a solution

**Comment by Songtech-0912** [comment] 2021-04-08 03:55
As the issue appears to be a problem with `GLFW` more than an issue with the AppImage itself, I recommend updating your system package for GLFW if you can. I cannot fix the issue directly, it would be up to the GLFW contributors to fix that issue, and they most likely have already fixed the bug.

I will close this issue, because it cannot be resolved unless GLFW patches the bug, and therefore I don't think it's worth continuing to discuss.

**Closed as completed by Songtech-0912** 2021-04-08 03:55 UTC
Labels: bug
